In [125]:
# US_Pollution_Script

In [126]:
# Import Libraries
import pandas as pd
import glob
import os

In [127]:
# Create Path
path = "Data_Sources"

In [128]:
# Test Directory of Files in Path
dir_list = os.listdir(path)
print(dir_list)

['annual_aqi_by_cbsa_2012.csv', 'annual_aqi_by_cbsa_2013.csv', 'annual_aqi_by_cbsa_2014.csv', 'annual_aqi_by_cbsa_2015.csv', 'annual_aqi_by_cbsa_2016.csv', 'annual_aqi_by_cbsa_2017.csv', 'annual_aqi_by_cbsa_2018.csv', 'annual_aqi_by_cbsa_2019.csv', 'annual_aqi_by_cbsa_2020.csv', 'annual_aqi_by_cbsa_2021.csv', 'annual_aqi_by_cbsa_2022.csv']

In [129]:
# Test Data Source
twelve = pd.read_csv('Data_Sources/annual_aqi_by_cbsa_2012.csv')

In [130]:
twelve.head(10)

,CBSA,CBSA Code,Year,Days with AQI,Good Days,Moderate Days,Unhealthy for Sensitive Groups Days,Unhealthy Days,Very Unhealthy Days,Hazardous Days,Max AQI,90th Percentile AQI,Median AQI,Days CO,Days NO2,Days Ozone,Days PM2.5,Days PM10
0,"Aberdeen, SD",10100,2012,123,104,19,0,0,0,0,77,53,28,0,0,0,109,14
1,"Aberdeen, WA",10140,2012,366,348,18,0,0,0,0,81,42,20,0,0,0,366,0
2,"Adjuntas, PR",10260,2012,77,74,3,0,0,0,0,66,36,18,0,0,0,77,0
3,"Adrian, MI",10300,2012,243,142,76,21,4,0,0,187,101,48,0,0,174,69,0
4,"Akron, OH",10420,2012,366,186,173,6,1,0,0,164,78,50,81,0,98,187,0
5,"Albany, GA",10500,2012,360,254,104,2,0,0,0,124,63,38,0,0,0,359,1
6,"Albany, OR",10540,2012,366,319,47,0,0,0,0,91,53,23,0,0,0,366,0
7,"Albany-Schenectady-Troy, NY",10580,2012,366,294,64,8,0,0,0,143,60,39,1,0,272,93,0
8,"Albuquerque, NM",10740,2012,366,100,241,23,1,1,0,291,96,60,0,2,228,105,31
9,"Alexandria, LA",10780,2012,362,177,185,0,0,0,0,88,66,52,0,0,0,362,0

In [131]:
# Get all files from path
all_files = glob.glob(path + "/*.csv")
print(all_files)

['Data_Sources\\annual_aqi_by_cbsa_2012.csv', 'Data_Sources\\annual_aqi_by_cbsa_2013.csv', 'Data_Sources\\annual_aqi_by_cbsa_2014.csv', 'Data_Sources\\annual_aqi_by_cbsa_2015.csv', 'Data_Sources\\annual_aqi_by_cbsa_2016.csv', 'Data_Sources\\annual_aqi_by_cbsa_2017.csv', 'Data_Sources\\annual_aqi_by_cbsa_2018.csv', 'Data_Sources\\annual_aqi_by_cbsa_2019.csv', 'Data_Sources\\annual_aqi_by_cbsa_2020.csv', 'Data_Sources\\annual_aqi_by_cbsa_2021.csv', 'Data_Sources\\annual_aqi_by_cbsa_2022.csv']

In [132]:
# Read each file into DataFrame
df_list = (pd.read_csv(file) for file in all_files)

In [133]:
# Concatenate All Files into one Dataframe
full_df = pd.concat(df_list, axis=0)

# Check Head for 2012 Data
full_df.head(10)

,CBSA,CBSA Code,Year,Days with AQI,Good Days,Moderate Days,Unhealthy for Sensitive Groups Days,Unhealthy Days,Very Unhealthy Days,Hazardous Days,Max AQI,90th Percentile AQI,Median AQI,Days CO,Days NO2,Days Ozone,Days PM2.5,Days PM10
0,"Aberdeen, SD",10100,2012,123,104,19,0,0,0,0,77,53,28,0,0,0,109,14
1,"Aberdeen, WA",10140,2012,366,348,18,0,0,0,0,81,42,20,0,0,0,366,0
2,"Adjuntas, PR",10260,2012,77,74,3,0,0,0,0,66,36,18,0,0,0,77,0
3,"Adrian, MI",10300,2012,243,142,76,21,4,0,0,187,101,48,0,0,174,69,0
4,"Akron, OH",10420,2012,366,186,173,6,1,0,0,164,78,50,81,0,98,187,0
5,"Albany, GA",10500,2012,360,254,104,2,0,0,0,124,63,38,0,0,0,359,1
6,"Albany, OR",10540,2012,366,319,47,0,0,0,0,91,53,23,0,0,0,366,0
7,"Albany-Schenectady-Troy, NY",10580,2012,366,294,64,8,0,0,0,143,60,39,1,0,272,93,0
8,"Albuquerque, NM",10740,2012,366,100,241,23,1,1,0,291,96,60,0,2,228,105,31
9,"Alexandria, LA",10780,2012,362,177,185,0,0,0,0,88,66,52,0,0,0,362,0

In [134]:
# Check Tail for 2022 Data
full_df.tail(10)

,CBSA,CBSA Code,Year,Days with AQI,Good Days,Moderate Days,Unhealthy for Sensitive Groups Days,Unhealthy Days,Very Unhealthy Days,Hazardous Days,Max AQI,90th Percentile AQI,Median AQI,Days CO,Days NO2,Days Ozone,Days PM2.5,Days PM10
486,"Wilmington, NC",48900,2022,271,253,18,0,0,0,0,80,47,36,0,0,191,80,0
487,"Wilmington, OH",48940,2022,214,187,26,1,0,0,0,140,54,41,0,0,214,0,0
488,"Winchester, VA-WV",49020,2022,208,172,36,0,0,0,0,88,54,38,0,0,98,110,0
489,"Winston-Salem, NC",49180,2022,243,177,65,1,0,0,0,137,59,44,0,3,143,97,0
490,"Worcester, MA-CT",49340,2022,243,200,43,0,0,0,0,93,57,42,0,9,156,78,0
491,"Yakima, WA",49420,2022,212,164,46,2,0,0,0,109,63,29,0,0,0,210,2
492,"York-Hanover, PA",49620,2022,298,230,67,1,0,0,0,105,61,40,0,57,101,140,0
493,"Youngstown-Warren-Boardman, OH-PA",49660,2022,243,186,53,4,0,0,0,136,61,43,0,0,183,60,0
494,"Yuba City, CA",49700,2022,181,116,64,1,0,0,0,102,76,46,0,0,107,74,0
495,"Yuma, AZ",49740,2022,273,169,95,9,0,0,0,142,80,46,0,0,173,32,68

In [135]:
# Check all years of data (2012-2022)
full_df.sample(25)

,CBSA,CBSA Code,Year,Days with AQI,Good Days,Moderate Days,Unhealthy for Sensitive Groups Days,Unhealthy Days,Very Unhealthy Days,Hazardous Days,Max AQI,90th Percentile AQI,Median AQI,Days CO,Days NO2,Days Ozone,Days PM2.5,Days PM10
77,"Champaign-Urbana, IL",16580,2019,365,281,84,0,0,0,0,100,61,42,0,0,235,130,0
170,"Fort Payne, AL",22840,2014,360,313,47,0,0,0,0,90,54,38,0,0,300,60,0
235,"Kapaa, HI",28180,2019,363,362,1,0,0,0,0,66,26,13,0,144,0,219,0
119,"Decatur, IL",19500,2012,366,220,136,10,0,0,0,126,74,45,0,0,195,171,0
370,"Portsmouth, OH",39020,2016,366,356,9,1,0,0,0,129,42,15,0,0,0,119,247
280,"Lynchburg, VA",31340,2017,114,110,4,0,0,0,0,60,44,26,0,0,0,114,0
444,"Sonora, CA",43760,2013,364,284,78,2,0,0,0,119,64,43,0,0,364,0,0
445,"St. Cloud, MN",41060,2019,344,313,31,0,0,0,0,93,49,32,0,0,211,133,0
358,"Pensacola-Ferry Pass-Brent, FL",37860,2012,366,264,98,4,0,0,0,115,71,43,0,0,208,158,0
492,"Waterloo-Cedar Falls, IA",47940,2019,363,286,77,0,0,0,0,90,61,39,0,0,193,170,0
358,"Peoria, IL",37900,2015,365,269,96,0,0,0,0,90,62,42,0,0,208,157,0
375,"Racine, WI",39540,2019,203,174,28,1,0,0,0,115,58,39,0,0,203,0,0
215,"Indianapolis-Carmel-Anderson, IN",26900,2021,365,154,204,7,0,0,0,114,80,53,0,8,93,264,0
215,"Hot Springs, AR",26300,2015,120,97,23,0,0,0,0,72,55,34,0,0,0,120,0
417,"Santa Fe, NM",42140,2014,365,306,59,0,0,0,0,87,56,43,0,0,358,7,0
473,"Traverse City, MI",45900,2013,183,140,42,1,0,0,0,119,71,40,0,0,183,0,0
144,"Ellensburg, WA",21260,2016,366,310,50,6,0,0,0,143,58,19,0,0,0,366,0
294,"Mobile, AL",33660,2022,180,143,37,0,0,0,0,93,58,42,0,0,73,107,0
156,"Fargo, ND-MN",22020,2021,363,278,68,8,9,0,0,192,72,37,0,5,198,160,0
496,"Walla Walla, WA",47460,2012,364,326,38,0,0,0,0,92,51,21,0,0,0,364,0
237,"Kalispell, MT",28060,2016,366,326,40,0,0,0,0,77,51,35,0,0,238,79,49
245,"Laconia, NH",29060,2021,365,346,18,1,0,0,0,110,44,28,0,0,188,177,0
345,"Omaha-Council Bluffs, NE-IA",36540,2012,366,129,217,20,0,0,0,140,90,56,0,0,113,113,140
125,"Dodge City, KS",19980,2020,302,297,5,0,0,0,0,79,29,11,0,0,0,0,302
315,"Montgomery, AL",33860,2012,280,206,73,1,0,0,0,102,62,43,0,0,196,84,0

In [136]:
# Check Record Count (should = 5680 rows)
len(full_df.index)

5680

In [137]:
# Text to columns CBSA to seperate State
full_df[['City', 'State']] = full_df['CBSA'].str.split(',',expand=True)
full_df.head(10)

,CBSA,CBSA Code,Year,Days with AQI,Good Days,Moderate Days,Unhealthy for Sensitive Groups Days,Unhealthy Days,Very Unhealthy Days,Hazardous Days,Max AQI,90th Percentile AQI,Median AQI,Days CO,Days NO2,Days Ozone,Days PM2.5,Days PM10,City,State
0,"Aberdeen, SD",10100,2012,123,104,19,0,0,0,0,77,53,28,0,0,0,109,14,Aberdeen,SD
1,"Aberdeen, WA",10140,2012,366,348,18,0,0,0,0,81,42,20,0,0,0,366,0,Aberdeen,WA
2,"Adjuntas, PR",10260,2012,77,74,3,0,0,0,0,66,36,18,0,0,0,77,0,Adjuntas,PR
3,"Adrian, MI",10300,2012,243,142,76,21,4,0,0,187,101,48,0,0,174,69,0,Adrian,MI
4,"Akron, OH",10420,2012,366,186,173,6,1,0,0,164,78,50,81,0,98,187,0,Akron,OH
5,"Albany, GA",10500,2012,360,254,104,2,0,0,0,124,63,38,0,0,0,359,1,Albany,GA
6,"Albany, OR",10540,2012,366,319,47,0,0,0,0,91,53,23,0,0,0,366,0,Albany,OR
7,"Albany-Schenectady-Troy, NY",10580,2012,366,294,64,8,0,0,0,143,60,39,1,0,272,93,0,Albany-Schenectady-Troy,NY
8,"Albuquerque, NM",10740,2012,366,100,241,23,1,1,0,291,96,60,0,2,228,105,31,Albuquerque,NM
9,"Alexandria, LA",10780,2012,362,177,185,0,0,0,0,88,66,52,0,0,0,362,0,Alexandria,LA

In [138]:
# Determine 5 highest "Median AQI" by "State" for each "Year"

In [139]:
# 2012
twentytwelve = full_df.loc[full_df['Year'] == 2012].sort_values(by='Median AQI', ascending=False).iloc[:15]
twentytwelve

,CBSA,CBSA Code,Year,Days with AQI,Good Days,Moderate Days,Unhealthy for Sensitive Groups Days,Unhealthy Days,Very Unhealthy Days,Hazardous Days,Max AQI,90th Percentile AQI,Median AQI,Days CO,Days NO2,Days Ozone,Days PM2.5,Days PM10,City,State
391,"Riverside-San Bernardino-Ontario, CA",40140,2012,366,16,168,110,63,9,0,233,172,100,0,4,193,134,35,Riverside-San Bernardino-Ontario,CA
361,"Phoenix-Mesa-Scottsdale, AZ",38060,2012,366,23,232,92,11,4,4,594,133,84,0,10,133,41,182,Phoenix-Mesa-Scottsdale,AZ
279,"Los Angeles-Long Beach-Anaheim, CA",31080,2012,366,32,202,95,35,2,0,207,151,84,0,19,176,169,2,Los Angeles-Long Beach-Anaheim,CA
30,"Bakersfield, CA",12540,2012,366,64,160,92,49,1,0,202,154,84,0,0,218,143,5,Bakersfield,CA
493,"Visalia-Porterville, CA",47300,2012,366,91,137,98,40,0,0,195,151,80,0,0,243,122,1,Visalia-Porterville,CA
171,"Fresno, CA",23420,2012,366,77,155,92,41,1,0,212,151,80,0,1,222,143,0,Fresno,CA
198,"Hanford-Corcoran, CA",25260,2012,366,117,183,60,6,0,0,172,114,66,0,0,210,137,19,Hanford-Corcoran,CA
263,"Las Vegas-Henderson-Paradise, NV",29820,2012,366,102,211,47,6,0,0,180,112,64,0,8,270,81,7,Las Vegas-Henderson-Paradise,NV
286,"Madera, CA",31460,2012,366,102,183,70,11,0,0,200,129,64,0,0,210,149,7,Madera,CA
400,"Rome, GA",40660,2012,365,49,316,0,0,0,0,99,81,64,0,0,0,365,0,Rome,GA
413,"San Diego-Carlsbad, CA",41740,2012,366,71,259,35,1,0,0,165,100,64,0,17,147,171,31,San Diego-Carlsbad,CA
87,"Chicago-Naperville-Elgin, IL-IN-WI",16980,2012,366,75,241,39,10,1,0,206,115,63,0,36,96,211,23,Chicago-Naperville-Elgin,IL-IN-WI
122,"Denver-Aurora-Lakewood, CO",19740,2012,366,112,184,63,7,0,0,190,115,63,0,74,256,28,8,Denver-Aurora-Lakewood,CO
312,"Modesto, CA",33700,2012,366,123,164,67,11,1,0,201,125,63,0,1,202,162,1,Modesto,CA
406,"Sacramento--Roseville--Arden-Arcade, CA",40900,2012,366,128,159,66,12,1,0,201,126,63,0,4,252,109,1,Sacramento--Roseville--Arden-Arcade,CA

In [140]:
# 2013
twentythirteen = full_df.loc[full_df['Year'] == 2013].sort_values(by='Median AQI', ascending=False).iloc[:15]

In [141]:
# 2014
twentyfourteen = full_df.loc[full_df['Year'] == 2014].sort_values(by='Median AQI', ascending=False).iloc[:15]

In [142]:
# 2015
twentyfifteen = full_df.loc[full_df['Year'] == 2015].sort_values(by='Median AQI', ascending=False).iloc[:15]

In [143]:
# 2016
twentysixteen = full_df.loc[full_df['Year'] == 2016].sort_values(by='Median AQI', ascending=False).iloc[:15]

In [144]:
# 2017
twentyseventeen = full_df.loc[full_df['Year'] == 2017].sort_values(by='Median AQI', ascending=False).iloc[:15]

In [145]:
# 2018
twentyeighteen = full_df.loc[full_df['Year'] == 2018].sort_values(by='Median AQI', ascending=False).iloc[:15]

In [146]:
# 2019
twentynineteen = full_df.loc[full_df['Year'] == 2019].sort_values(by='Median AQI', ascending=False).iloc[:15]

In [147]:
# 2020
twentytwenty = full_df.loc[full_df['Year'] == 2020].sort_values(by='Median AQI', ascending=False).iloc[:15]

In [148]:
# 2021
twentyone = full_df.loc[full_df['Year'] == 2021].sort_values(by='Median AQI', ascending=False).iloc[:15]

In [149]:
# 2022
twentytwo = full_df.loc[full_df['Year'] == 2022].sort_values(by='Median AQI', ascending=False).iloc[:15]

In [210]:
# Concate dataframes for Top 15 records for each year (above dfs combined)
top_15_df = pd.concat([twentytwelve, twentythirteen, twentyfourteen, twentyfifteen, twentysixteen, twentyseventeen, twentyeighteen, twentynineteen, twentytwenty, twentyone, twentytwo])
top_15_df

,CBSA,CBSA Code,Year,Days with AQI,Good Days,Moderate Days,Unhealthy for Sensitive Groups Days,Unhealthy Days,Very Unhealthy Days,Hazardous Days,Max AQI,90th Percentile AQI,Median AQI,Days CO,Days NO2,Days Ozone,Days PM2.5,Days PM10,City,State
391,"Riverside-San Bernardino-Ontario, CA",40140,2012,366,16,168,110,63,9,0,233,172,100,0,4,193,134,35,Riverside-San Bernardino-Ontario,CA
361,"Phoenix-Mesa-Scottsdale, AZ",38060,2012,366,23,232,92,11,4,4,594,133,84,0,10,133,41,182,Phoenix-Mesa-Scottsdale,AZ
279,"Los Angeles-Long Beach-Anaheim, CA",31080,2012,366,32,202,95,35,2,0,207,151,84,0,19,176,169,2,Los Angeles-Long Beach-Anaheim,CA
30,"Bakersfield, CA",12540,2012,366,64,160,92,49,1,0,202,154,84,0,0,218,143,5,Bakersfield,CA
493,"Visalia-Porterville, CA",47300,2012,366,91,137,98,40,0,0,195,151,80,0,0,243,122,1,Visalia-Porterville,CA
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
136,"El Centro, CA",20940,2022,238,82,122,23,4,2,5,762,114,57,0,4,74,42,118,El Centro,CA
138,"El Paso, TX",21340,2022,213,75,123,14,1,0,0,163,94,56,1,10,117,74,11,El Paso,TX
397,"San Luis Obispo-Paso Robles-Arroyo Grande, CA",42020,2022,181,64,115,2,0,0,0,115,72,55,0,0,80,92,9,San Luis Obispo-Paso Robles-Arroyo Grande,CA
122,"Detroit-Warren-Dearborn, MI",19820,2022,182,75,97,10,0,0,0,133,84,54,1,8,50,116,7,Detroit-Warren-Dearborn,MI
251,"Las Cruces, NM",29740,2022,273,118,127,23,1,2,2,375,101,54,0,11,186,15,61,Las Cruces,NM

In [227]:
# Top average most polluted states from 2012-2022
top_avg_state = top_15_df.groupby("State")["Median AQI"].mean().sort_values(ascending=False)
top_avg_state

State
 AZ             86.000000
 CA             72.045872
 GA             64.000000
 CO             61.454545
 HI             61.000000
 MT             61.000000
 NV             59.700000
 UT             59.500000
 IL-IN-WI       59.200000
 OH-KY-IN       59.000000
 PA-NJ-DE-MD    59.000000
 NM             57.666667
 PA             57.333333
 TX             56.000000
 MI             54.000000
 IN             54.000000
 MO-IL          54.000000
Name: Median AQI, dtype: float64

In [ ]:
# Create full database records for machine learning

In [249]:
# California
CA_data = full_df[full_df["CBSA"].str.contains("CA")]
CA_data.head(5)

,CBSA,CBSA Code,Year,Days with AQI,Good Days,Moderate Days,Unhealthy for Sensitive Groups Days,Unhealthy Days,Very Unhealthy Days,Hazardous Days,Max AQI,90th Percentile AQI,Median AQI,Days CO,Days NO2,Days Ozone,Days PM2.5,Days PM10,City,State
30,"Bakersfield, CA",12540,2012,366,64,160,92,49,1,0,202,154,84,0,0,218,143,5,Bakersfield,CA
46,"Bishop, CA",13860,2012,366,204,133,15,4,2,8,3812,93,48,0,0,280,10,76,Bishop,CA
88,"Chico, CA",17020,2012,366,170,165,23,8,0,0,186,97,53,0,0,230,136,0,Chico,CA
93,"Clearlake, CA",17340,2012,362,336,23,3,0,0,0,143,47,35,0,0,360,2,0,Clearlake,CA
110,"Crescent City, CA",18860,2012,119,119,0,0,0,0,0,45,26,10,0,0,0,79,40,Crescent City,CA

In [251]:
# Arizona
AZ_data = full_df[full_df["CBSA"].str.contains("AZ")]
AZ_data.head(5)

,CBSA,CBSA Code,Year,Days with AQI,Good Days,Moderate Days,Unhealthy for Sensitive Groups Days,Unhealthy Days,Very Unhealthy Days,Hazardous Days,Max AQI,90th Percentile AQI,Median AQI,Days CO,Days NO2,Days Ozone,Days PM2.5,Days PM10,City,State
161,"Flagstaff, AZ",22380,2012,366,238,113,15,0,0,0,133,80,46,0,0,354,12,0,Flagstaff,AZ
256,"Lake Havasu City-Kingman, AZ",29420,2012,240,235,4,1,0,0,0,116,35,19,0,0,0,48,192,Lake Havasu City-Kingman,AZ
337,"Nogales, AZ",35700,2012,337,229,107,1,0,0,0,107,62,41,0,0,0,24,313,Nogales,AZ
357,"Payson, AZ",37740,2012,364,148,187,28,1,0,0,160,97,54,0,0,199,3,162,Payson,AZ
361,"Phoenix-Mesa-Scottsdale, AZ",38060,2012,366,23,232,92,11,4,4,594,133,84,0,10,133,41,182,Phoenix-Mesa-Scottsdale,AZ

In [252]:
# Georgia
GA_data = full_df[full_df["CBSA"].str.contains("GA")]
GA_data.head(5)

,CBSA,CBSA Code,Year,Days with AQI,Good Days,Moderate Days,Unhealthy for Sensitive Groups Days,Unhealthy Days,Very Unhealthy Days,Hazardous Days,Max AQI,90th Percentile AQI,Median AQI,Days CO,Days NO2,Days Ozone,Days PM2.5,Days PM10,City,State
5,"Albany, GA",10500,2012,360,254,104,2,0,0,0,124,63,38,0,0,0,359,1,Albany,GA
13,"Americus, GA",11140,2012,233,204,29,0,0,0,0,97,54,40,0,0,233,0,0,Americus,GA
24,"Athens-Clarke County, GA",12020,2012,366,247,113,5,1,0,0,153,67,43,0,0,140,226,0,Athens-Clarke County,GA
25,"Atlanta-Sandy Springs-Roswell, GA",12060,2012,366,106,232,19,8,1,0,218,97,61,0,1,142,223,0,Atlanta-Sandy Springs-Roswell,GA
27,"Augusta-Richmond County, GA-SC",12260,2012,366,224,136,5,1,0,0,151,69,45,0,0,134,232,0,Augusta-Richmond County,GA-SC

In [253]:
# Colorado
CO_data = full_df[full_df["CBSA"].str.contains("CO")]
CO_data.head(5)

,CBSA,CBSA Code,Year,Days with AQI,Good Days,Moderate Days,Unhealthy for Sensitive Groups Days,Unhealthy Days,Very Unhealthy Days,Hazardous Days,Max AQI,90th Percentile AQI,Median AQI,Days CO,Days NO2,Days Ozone,Days PM2.5,Days PM10,City,State
54,"Boulder, CO",14500,2012,359,191,133,31,4,0,0,172,100,48,0,0,337,19,3,Boulder,CO
59,"Breckenridge, CO",14720,2012,123,119,4,0,0,0,0,64,31,12,0,0,0,0,123,Breckenridge,CO
76,"Ca¤on City, CO",15860,2012,57,56,1,0,0,0,0,54,30,15,0,0,0,0,57,Ca¤on City,CO
98,"Colorado Springs, CO",17820,2012,366,210,136,20,0,0,0,129,90,48,0,0,363,2,1,Colorado Springs,CO
109,"Craig, CO",18780,2012,361,266,94,1,0,0,0,105,64,44,0,0,361,0,0,Craig,CO

In [254]:
# Hawaii
HI_data = full_df[full_df["CBSA"].str.contains("HI")]
HI_data.head(5)

,CBSA,CBSA Code,Year,Days with AQI,Good Days,Moderate Days,Unhealthy for Sensitive Groups Days,Unhealthy Days,Very Unhealthy Days,Hazardous Days,Max AQI,90th Percentile AQI,Median AQI,Days CO,Days NO2,Days Ozone,Days PM2.5,Days PM10,City,State
208,"Hilo, HI",25900,2012,366,52,312,0,2,0,0,172,75,60,0,0,0,366,0,Hilo,HI
234,"Kahului-Wailuku-Lahaina, HI",27980,2012,349,334,15,0,0,0,0,64,40,25,0,0,0,349,0,Kahului-Wailuku-Lahaina,HI
238,"Kapaa, HI",28180,2012,365,351,14,0,0,0,0,60,45,27,16,15,0,334,0,Kapaa,HI
483,"Urban Honolulu, HI",46520,2012,366,335,31,0,0,0,0,75,48,33,0,0,129,232,5,Urban Honolulu,HI
208,"Hilo, HI",25900,2013,365,81,284,0,0,0,0,93,68,56,0,0,0,365,0,Hilo,HI

In [255]:
# Montana
MT_data = full_df[full_df["CBSA"].str.contains("MT")]
MT_data.head(5)

,CBSA,CBSA Code,Year,Days with AQI,Good Days,Moderate Days,Unhealthy for Sensitive Groups Days,Unhealthy Days,Very Unhealthy Days,Hazardous Days,Max AQI,90th Percentile AQI,Median AQI,Days CO,Days NO2,Days Ozone,Days PM2.5,Days PM10,City,State
44,"Billings, MT",13740,2012,362,331,31,0,0,0,0,94,45,18,0,0,0,362,0,Billings,MT
56,"Bozeman, MT",14580,2012,366,305,53,8,0,0,0,138,62,25,1,30,0,335,0,Bozeman,MT
68,"Butte-Silver Bow, MT",15580,2012,363,257,93,8,5,0,0,174,78,31,0,0,0,285,78,Butte-Silver Bow,MT
187,"Great Falls, MT",24500,2012,360,299,58,3,0,0,0,132,57,32,0,0,0,360,0,Great Falls,MT
204,"Helena, MT",25740,2012,366,271,88,7,0,0,0,148,67,40,0,0,208,158,0,Helena,MT

In [258]:
# Concatenate full dataframe with top 6 all records
top_polluted_states = pd.concat([CA_data, MT_data, HI_data, AZ_data, CO_data, GA_data])
top_polluted_states.sample(10)

,CBSA,CBSA Code,Year,Days with AQI,Good Days,Moderate Days,Unhealthy for Sensitive Groups Days,Unhealthy Days,Very Unhealthy Days,Hazardous Days,Max AQI,90th Percentile AQI,Median AQI,Days CO,Days NO2,Days Ozone,Days PM2.5,Days PM10,City,State
184,"Great Falls, MT",24500,2018,360,329,25,5,1,0,0,162,49,25,0,0,0,360,0,Great Falls,MT
198,"Hanford-Corcoran, CA",25260,2012,366,117,183,60,6,0,0,172,114,66,0,0,210,137,19,Hanford-Corcoran,CA
306,"Modesto, CA",33700,2017,365,156,146,55,8,0,0,185,112,58,0,1,228,128,8,Modesto,CA
495,"Warner Robins, GA",47580,2017,330,265,65,0,0,0,0,92,56,35,0,0,0,330,0,Warner Robins,GA
498,"Warner Robins, GA",47580,2013,351,251,100,0,0,0,0,87,59,38,0,0,0,351,0,Warner Robins,GA
184,"Grand Junction, CO",24300,2012,366,200,155,11,0,0,0,122,87,48,0,0,340,17,9,Grand Junction,CO
184,"Greeley, CO",24540,2017,365,211,146,7,1,0,0,154,77,47,0,0,273,92,0,Greeley,CO
5,"Albany, GA",10500,2014,359,216,142,1,0,0,0,111,65,45,0,0,0,359,0,Albany,GA
108,"Crescent City, CA",18860,2017,298,270,26,0,1,1,0,226,49,20,0,0,0,298,0,Crescent City,CA
61,"Brunswick, GA",15260,2019,279,254,25,0,0,0,0,80,50,36,0,0,224,55,0,Brunswick,GA

In [259]:
# Convert to csv file
top_polluted_states.to_csv('Top_6_Most_Polluted_US_States.csv')